#
# Playbook to deploy KAFKA
#
# Then run the playbook, like this:
#
# ansible-playbook kafka.yml --ask-sudo-pass -k --become --become-method=sudo
#
# And that's it!.
#
# The command will provision a Kafka cluster, a Zookeeper cluster and a Kerberos server with the machines
# referenced in the "hosts" file.

---
- hosts: "{{ hosts_destination | default('kafkabrokers') }}"
  gather_facts: true
  roles:
    - kafka
    - monit
    - kafkaszookeeper
...

